server:
  port: 8010
spring:
  application:
    name: city-comm
    port: 8888
  profiles:
    active: dev

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/