server:
  port: 8030
#datasource
spring:
  application:
    name: city-auth
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: dreamcity
    password: Root@123
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

mybatis:
  type-aliases-package: com.dream.city.domain.mapper
  mapper-locations: classpath:/mappers/*.xml

#mybatis
auth:
  secret: oKKLJOoasdl