server:
  port: 8060
spring:
  application:
    name: city-user


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/
